server:
  port: 20002

spring:
  application:
    name: eureka-consumers

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10      # 每隔10秒，向服务中心发送一条续约指令
    lease-expiration-duration-in-seconds: 30   # 如果30秒内，依然没有收到续约请求，判定服务过期

