spring:
  cloud:
    gateway:
      routes:
        - id: product
          uri: lb://product-center
          predicates:
           - Query=company,product
        - id: order
          uri: lb://order-center
          predicates:
            - Query=company,order