spring:
  cloud:
    gateway:
      routes:
       - id: mic-accurate #id必须要唯一
         uri: lb://product-center
         #表示:访问http://localhost:8888/product/selectProductInfoById/1
         #会转发到http://product-center/product/selectProductInfoById/1
         #而http://localhost:8888/selectProductInfoById/2 不会被转发
         predicates:
          - Path=/product/selectProductInfoById/1