spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri:    #git 仓库位置
          search-paths:   #配置仓库路径下的相对搜索位置，可以配置多个
          username:
          password:

server:
  port: 8787

